### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Ansif** [telmomarques/animate-plus.js#2]
Hi, 

Thanks for great plugin! :+1: 

I'm getting this error from your animate-plus.min.js file?
TypeError: this.map[e].animate is not a function

Can you please let me know the solution for this issue?

Thanks!

**Comment by telmomarques** [comment]
Hi,

Could you provide a link to the page so I can analyze this issue?

**Comment by Ansif** [comment]
Hi,

Thanks for your quick reply!

You can check that error in this page :
[URL REMOVED]

I've used your script for banner little animation! 
[SCREENSHOT REMOVED]

Regards,
Ansif

**Comment by telmomarques** [comment]
Hi,

You're defining two "data-animation-delay" values but only specifying one animation in "data-animations".

For example, "1200ms,0s" should be only "1200ms".

Let me know if this solves the problem.

**Comment by Ansif** [comment]
Hi,

Thanks for your quick response! 

I've removed that second value. But no luck. :(

**Comment by telmomarques** [comment]
Hi,

Could you temporarily switch to the non-minified version so I can check?
I'm unable to reproduce this issue locally.

**Comment by Ansif** [comment]
Sorry, now you can check! :)

**Comment by telmomarques** [comment]
Hi,

I'm still seeing the animate-plus.min.js. Are you sure you switched to the animate-plus.js?

**Comment by Ansif** [comment]
Hi,

Sorry i've replaced animate-plus.js, but still file name is : animate-plus.min.js 

Thanks! :)

**Comment by telmomarques** [comment]
Hi,

I've just commited a fix for this issue. Please re-download the script and test again :)

**Comment by Ansif** [comment]
Fixed! :+1:
